#pragma once

#define SOLUTION_PRODUCTVERSION_NUMBER 1, 0, 0, 0
#define SOLUTION_PRODUCTVERSION_STRING "1.0.0"
#define SOLUTION_FILEVERSION_NUMBER SOLUTION_PRODUCTVERSION_NUMBER
#define SOLUTION_FILEVERSION_STRING SOLUTION_PRODUCTVERSION_STRING

#define SOLUTION_PRODUCTNAME "MyPass"
#define SOLUTION_INTERNALNAME "MyPass.exe"
#define SOLUTION_ORIGINALFILENAME SOLUTION_INTERNALNAME

#define SOLUTION_COMPANYNAME "Mima"
#define SOLUTION_FILEDESCRIPTION "Offline Password Manager"
#define SOLUTION_LEGALCOPYRIGHT "Copyright (C) 2026"
